# .github/workflows/make.yml

name: Bean Stock Remote Submodule Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  dispatch:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: spaced-out-thoughts-dev-foundation/bean_stock
          event-type: trigger-workflow